# -*- coding: utf-8 -*-
"""exposys_final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/135cD5b28LFiwxSYstijnT02poOjB2iFo
"""

import numpy as np
import pandas as pd
import seaborn as sns

df=pd.read_csv('/content/50_Startups.csv')

df

df.describe()

mean1 = df['R&D Spend'].mean()

mean2=df['Marketing Spend'].mean()

df['R&D Spend'] = df['R&D Spend'].replace(0, mean1)
df['Marketing Spend'] = df['Marketing Spend'].replace(0, mean2)

df

sns.pairplot(df)

correlation_matrix=df.corr()
sns.heatmap(correlation_matrix,annot=True)

#R&D Spend has the maximum correlation with Profit our target variable

X=df[['R&D Spend']]
y=df['Profit']

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

from sklearn.linear_model import LinearRegression
model=LinearRegression()
model.fit(X_train,y_train)

y_pred=model.predict(X_test)

from sklearn.metrics import mean_squared_error
mse=mean_squared_error(y_test,y_pred)
from sklearn.metrics import mean_absolute_error
mae=mean_absolute_error(y_test,y_pred)

print("Mean Squared Error",mse)
print("Mean Absolute Error",mae)

from sklearn.metrics import r2_score
r2s=r2_score(y_test,y_pred)
print("R2 Score",r2s)

#This is the best accuracy we get till now


